In [1]:
import pandas as pd
import numpy as np
frame = pd.DataFrame(np.random.randn(4,3),
                    columns=list('bde'),
                    index=['台北','台中','台南','高雄'])

frame

           b         d         e
台北  0.059945  0.546182 -0.664588
台中 -0.021443 -0.243796  0.752235
台南 -1.401191 -0.517729 -0.109336
高雄  1.133073 -2.738078 -1.607422

In [2]:
np.abs(frame)

           b         d         e
台北  0.059945  0.546182  0.664588
台中  0.021443  0.243796  0.752235
台南  1.401191  0.517729  0.109336
高雄  1.133073  2.738078  1.607422

In [3]:
np.sum(frame)

/home/vscode/.local/lib/python3.10/site-packages/numpy/core/fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

b   -0.229616
d   -2.953421
e   -1.629110
dtype: float64

In [4]:
frame

           b         d         e
台北  0.059945  0.546182 -0.664588
台中 -0.021443 -0.243796  0.752235
台南 -1.401191 -0.517729 -0.109336
高雄  1.133073 -2.738078 -1.607422

In [5]:
import numpy as np
import pandas as pd

scores = np.random.randint(50,101,size=(50,5))
scores_df = pd.DataFrame(scores,columns=['國文', '英文', '數學', '地理', '歷史'],index=range(1,51))
scores_df

     國文  英文   數學   地理   歷史
1    84  82   74   93   75
2    76  60   61   86   63
3    71  93   78   87   84
4    80  53   53   92   87
5    68  62   79   50   87
6    93  82   81   54   73
7    59  73   75   60   76
8    56  89   87   82   80
9    87  86   83   92   62
10   91  80   51   64   94
11   96  97   68   82   60
12   89  75   71   87   79
13   59  96   54   96   91
14   54  88   88   76   55
15   56  88   69   65  100
16   79  94   96   90   97
17   60  72   56   84   50
18   95  86   94  100   66
19   93  81   75   65   71
20   55  62   90   77   72
21   61  70   68   84   78
22   79  79   81   85   78
23   76  73   60   84   65
24   52  86   81   72   96
25   60  77   78   74   77
26   75  67   64   56   76
27  100  61   84   88   73
28   97  53   77   75   87
29   80  69   90   62   62
30   72  76  100   73   53
31   64  80   57   53   70
32   70  98   93   62   65
33   54  87   95   55   51
34   59  94   60   58   65
35   57  80   99   87   52
36   67  85   88   67   59
37   91  89   73   73   55
38   71  89   89   96   51
39   76  64   57   84   63
40   57  52   67   85   56
41   88  63   52   69  100
42   66  86   77   52   93
43   69  50   74   80   87
44   81  78   54   89   67
45   86  98   91   71   99
46   85  73   86   90   54
47   60  77   91   77   55
48   99  55   53   89   78
49   85  86   77   70   91
50   99  70   84   84   52

In [6]:
# dataframe使用統計的方法,sum,mean,max,min,median,count,std
scores_sum = scores_df.sum(axis=1)
#scores_average = scores_sum / 5.0
scores_average = scores_df.mean(axis=1)
scores_average
scores_df['總分'] = scores_sum
scores_df['平均'] = scores_average
scores_df

     國文  英文   數學   地理   歷史   總分    平均
1    84  82   74   93   75  408  81.6
2    76  60   61   86   63  346  69.2
3    71  93   78   87   84  413  82.6
4    80  53   53   92   87  365  73.0
5    68  62   79   50   87  346  69.2
6    93  82   81   54   73  383  76.6
7    59  73   75   60   76  343  68.6
8    56  89   87   82   80  394  78.8
9    87  86   83   92   62  410  82.0
10   91  80   51   64   94  380  76.0
11   96  97   68   82   60  403  80.6
12   89  75   71   87   79  401  80.2
13   59  96   54   96   91  396  79.2
14   54  88   88   76   55  361  72.2
15   56  88   69   65  100  378  75.6
16   79  94   96   90   97  456  91.2
17   60  72   56   84   50  322  64.4
18   95  86   94  100   66  441  88.2
19   93  81   75   65   71  385  77.0
20   55  62   90   77   72  356  71.2
21   61  70   68   84   78  361  72.2
22   79  79   81   85   78  402  80.4
23   76  73   60   84   65  358  71.6
24   52  86   81   72   96  387  77.4
25   60  77   78   74   77  366  73.2
26   75  67   64   56   76  338  67.6
27  100  61   84   88   73  406  81.2
28   97  53   77   75   87  389  77.8
29   80  69   90   62   62  363  72.6
30   72  76  100   73   53  374  74.8
31   64  80   57   53   70  324  64.8
32   70  98   93   62   65  388  77.6
33   54  87   95   55   51  342  68.4
34   59  94   60   58   65  336  67.2
35   57  80   99   87   52  375  75.0
36   67  85   88   67   59  366  73.2
37   91  89   73   73   55  381  76.2
38   71  89   89   96   51  396  79.2
39   76  64   57   84   63  344  68.8
40   57  52   67   85   56  317  63.4
41   88  63   52   69  100  372  74.4
42   66  86   77   52   93  374  74.8
43   69  50   74   80   87  360  72.0
44   81  78   54   89   67  369  73.8
45   86  98   91   71   99  445  89.0
46   85  73   86   90   54  388  77.6
47   60  77   91   77   55  360  72.0
48   99  55   53   89   78  374  74.8
49   85  86   77   70   91  409  81.8
50   99  70   84   84   52  389  77.8

In [7]:
#scores_df[['國文', '英文', '數學', '地理', '歷史']]
#dataFrame應用自訂的function
from pandas import Series

def get_level(s:Series):
    average = s.mean()
    if average < 60:
        return '不及格'
    elif average < 80:
        return '甲'
    else:
        return '優'


scores_df['等級'] = scores_df[['國文', '英文', '數學', '地理', '歷史']].apply(get_level,axis=1)

In [8]:
scores_df

     國文  英文   數學   地理   歷史   總分    平均 等級
1    84  82   74   93   75  408  81.6  優
2    76  60   61   86   63  346  69.2  甲
3    71  93   78   87   84  413  82.6  優
4    80  53   53   92   87  365  73.0  甲
5    68  62   79   50   87  346  69.2  甲
6    93  82   81   54   73  383  76.6  甲
7    59  73   75   60   76  343  68.6  甲
8    56  89   87   82   80  394  78.8  甲
9    87  86   83   92   62  410  82.0  優
10   91  80   51   64   94  380  76.0  甲
11   96  97   68   82   60  403  80.6  優
12   89  75   71   87   79  401  80.2  優
13   59  96   54   96   91  396  79.2  甲
14   54  88   88   76   55  361  72.2  甲
15   56  88   69   65  100  378  75.6  甲
16   79  94   96   90   97  456  91.2  優
17   60  72   56   84   50  322  64.4  甲
18   95  86   94  100   66  441  88.2  優
19   93  81   75   65   71  385  77.0  甲
20   55  62   90   77   72  356  71.2  甲
21   61  70   68   84   78  361  72.2  甲
22   79  79   81   85   78  402  80.4  優
23   76  73   60   84   65  358  71.6  甲
24   52  86   81   72   96  387  77.4  甲
25   60  77   78   74   77  366  73.2  甲
26   75  67   64   56   76  338  67.6  甲
27  100  61   84   88   73  406  81.2  優
28   97  53   77   75   87  389  77.8  甲
29   80  69   90   62   62  363  72.6  甲
30   72  76  100   73   53  374  74.8  甲
31   64  80   57   53   70  324  64.8  甲
32   70  98   93   62   65  388  77.6  甲
33   54  87   95   55   51  342  68.4  甲
34   59  94   60   58   65  336  67.2  甲
35   57  80   99   87   52  375  75.0  甲
36   67  85   88   67   59  366  73.2  甲
37   91  89   73   73   55  381  76.2  甲
38   71  89   89   96   51  396  79.2  甲
39   76  64   57   84   63  344  68.8  甲
40   57  52   67   85   56  317  63.4  甲
41   88  63   52   69  100  372  74.4  甲
42   66  86   77   52   93  374  74.8  甲
43   69  50   74   80   87  360  72.0  甲
44   81  78   54   89   67  369  73.8  甲
45   86  98   91   71   99  445  89.0  優
46   85  73   86   90   54  388  77.6  甲
47   60  77   91   77   55  360  72.0  甲
48   99  55   53   89   78  374  74.8  甲
49   85  86   77   70   91  409  81.8  優
50   99  70   84   84   52  389  77.8  甲